AttributeError
Python 3.6.5: F:\Python3.6.5_V2\python.exe
Mon Mar 30 11:07:49 2020

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 D:\My_Codes\easylearn-fmri\eslearn\gui_test\easylearn_main_run.py in data_loading_fun(self=<__main__.EasylearnMainGUI object>)
  168         """
  169         print('data_loading_fun')
  170         self.data_loading = EasylearnDataLoadingRun(self.working_directory)
  171         self.data_loading.show()
  172 
self = <__main__.EasylearnMainGUI object>
self.data_loading = <PyQt5.QtWidgets.QPushButton object>
global EasylearnDataLoadingRun = <class 'easylearn_data_loading_run.EasylearnDataLoadingRun'>
self.working_directory = 'D:/My_Codes/easylearn-fmri/eslearn/gui_test'

 D:\My_Codes\easylearn-fmri\eslearn\gui_test\easylearn_data_loading_run.py in __init__(self=<easylearn_data_loading_run.EasylearnDataLoadingRun object>, working_directory='D:/My_Codes/easylearn-fmri/eslearn/gui_test')
   28             os.chdir(self.working_directory)
   29             cgitb.enable(format="text", display=1, logdir=os.path.join(self.working_directory, "log"))
   30             cgitb.handle(info=None)
   31         # set appearance
   32         self.set_run_appearance()
global cgitb = <module 'cgitb' from 'F:\\Python3.6.5_V2\\lib\\cgitb.py'>
cgitb.handle undefined
info undefined
AttributeError: module 'cgitb' has no attribute 'handle'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("module 'cgitb' has no attribute 'handle'",)
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "D:\My_Codes\easylearn-fmri\eslearn\gui_test\easylearn_main_run.py", line 170, in data_loading_fun
    self.data_loading = EasylearnDataLoadingRun(self.working_directory)
  File "D:\My_Codes\easylearn-fmri\eslearn\gui_test\easylearn_data_loading_run.py", line 30, in __init__
    cgitb.handle(info=None)
AttributeError: module 'cgitb' has no attribute 'handle'

